### ISSUE TITLE
Project File

### ISSUE THREAD

**Issue by Ironowl1907** [Ironowl1907/Zirconium#15]
Introduce a `.zr` project file format using **YAML** to manage core project metadata, asset/scene paths, and engine configurations. This file will serve as the central configuration manifest for Zirconium Engine projects.

---

### 📦 Goals

- ✅ Human-readable YAML structure
- ✅ Define project metadata (name, version, engine version)
- ✅ Track scenes and assets paths
- ✅ Store global configurations (window, scripting, modules)
- ✅ Local paths only — no absolute or platform-specific dependencies

---

### 📄 Example `.zr` File Structure (`project.zr`)
```yaml
project:
  name: MyAwesomeGame
  version: 0.1.0
  engine_version: 0.9.2

window:
  width: 1280
  height: 720
  fullscreen: false
  vsync: true

startup:
  scene: scenes/MainMenu.scene

paths:
  asset_dir: assets/
  scene_dir: scenes/
  script_dir: scripts/

scripting:
  backend: lua
  entry_script: scripts/init.lua

modules:
  physics: true
  audio: true
  networking: false
```

---

### 🛠 Tasks

- [x] Define `.zr` file format using YAML
- [x] Implement loader/parser for `.zr` files
- [x] Validate required fields (e.g., `project`, `startup.scene`)
- [x] Store relative paths only
- [ ] Initialize engine systems (window, scripting, etc.) from config
- [ ] Make it extensible for future settings (input mappings, locales, etc.)

---

### 📁 File Location

Each project will include this at the root:
```
MyAwesomeGame/
├── project.zr
├── assets/
├── scenes/
├── scripts/
```

---

### ✅ Acceptance Criteria

- Engine can load `.zr` file and initialize core systems
- Incorrect or missing fields result in clear errors
- Supports loading startup scene and assets
- Easy to edit manually
